name: flutter_local_notifications_example
description: Demonstrates how to use the flutter_local_notifications plugin.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  http: ^0.12.0
  path_provider: ^0.4.1
  shared_preferences: ^0.5.3+4
  bloc: ^0.14.0
  flutter_bloc: ^0.20.0
  equatable: ^0.1.5
  intl: ^0.15.8
  flutter_datetime_picker: ^1.2.5
  toast: ^0.1.5
  flutter_local_notifications: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
